version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    ports:
      - "5432:5432"

  # cloudbeaver:
  #   image: dbeaver/cloudbeaver
  #   restart: always
  #   ports:
  #     - 8080:8978